library(tidyverse)
library(lumi)
library(limma)
library(pander)
library(GEOquery)
library(illuminaHumanv4.db)
library(affy)
library(hgu133plus2.db)
library(edgeR)
library(plater)
library(lubridate)
library(patchwork) #https://github.com/thomasp85/patchwork, not on CRAN
library(conflicted)
library(drc)
library(writexl)
library(ggrepel)
library(lme4)
library(lmerTest)
# if "filter" or "select" is called, assume it's from dplyr
# prevents conflicts with bioconductor packages
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("select", "dplyr", quiet = TRUE) 
conflict_prefer("rename", "dplyr", quiet = TRUE)
conflict_prefer("slice", "dplyr", quiet = TRUE)
conflict_prefer("rowSums", "Matrix", quiet = TRUE)

source("R/get_data.R")
source("R/analysis_helpers.R")
source("R/plot_helpers.R")
source("R/style_functions.R")
